package AirMonitoring;


/**
* AirMonitoring/_EnvironmentalCentreStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Sunday, 8 April 2018 17:51:22 o'clock BST
*/

public class _EnvironmentalCentreStub extends org.omg.CORBA.portable.ObjectImpl implements AirMonitoring.EnvironmentalCentre
{

  public AirMonitoring.Reading[] readings ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("readings", true);
                $in = _invoke ($out);
                AirMonitoring.Reading $result[] = AirMonitoring.readingsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return readings (        );
            } finally {
                _releaseReply ($in);
            }
  } // readings

  public AirMonitoring.CentreInfo[] connectedCentres ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_connectedCentres", true);
                $in = _invoke ($out);
                AirMonitoring.CentreInfo $result[] = AirMonitoring.centreListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return connectedCentres (        );
            } finally {
                _releaseReply ($in);
            }
  } // connectedCentres

  public void connectedCentres (AirMonitoring.CentreInfo[] newConnectedCentres)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_connectedCentres", true);
                AirMonitoring.centreListHelper.write ($out, newConnectedCentres);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                connectedCentres (newConnectedCentres        );
            } finally {
                _releaseReply ($in);
            }
  } // connectedCentres

  public void registerRegionalCentre (AirMonitoring.CentreInfo info)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerRegionalCentre", true);
                AirMonitoring.CentreInfoHelper.write ($out, info);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerRegionalCentre (info        );
            } finally {
                _releaseReply ($in);
            }
  } // registerRegionalCentre

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AirMonitoring/EnvironmentalCentre:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _EnvironmentalCentreStub
