package AirMonitoring;


/**
* AirMonitoring/_RegionalCentreStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Sunday, 8 April 2018 17:51:22 o'clock BST
*/

public class _RegionalCentreStub extends org.omg.CORBA.portable.ObjectImpl implements AirMonitoring.RegionalCentre
{

  public AirMonitoring.StationInfo[] connectedDevices ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_get_connectedDevices", true);
                $in = _invoke ($out);
                AirMonitoring.StationInfo $result[] = AirMonitoring.stationListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return connectedDevices (        );
            } finally {
                _releaseReply ($in);
            }
  } // connectedDevices

  public void connectedDevices (AirMonitoring.StationInfo[] newConnectedDevices)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("_set_connectedDevices", true);
                AirMonitoring.stationListHelper.write ($out, newConnectedDevices);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                connectedDevices (newConnectedDevices        );
            } finally {
                _releaseReply ($in);
            }
  } // connectedDevices

  public AirMonitoring.CentreInfo centreInfo ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("centreInfo", true);
                $in = _invoke ($out);
                AirMonitoring.CentreInfo $result = AirMonitoring.CentreInfoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return centreInfo (        );
            } finally {
                _releaseReply ($in);
            }
  } // centreInfo

  public void setInfo (AirMonitoring.CentreInfo info)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setInfo", true);
                AirMonitoring.CentreInfoHelper.write ($out, info);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setInfo (info        );
            } finally {
                _releaseReply ($in);
            }
  } // setInfo

  public AirMonitoring.Reading[] readings ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("readings", true);
                $in = _invoke ($out);
                AirMonitoring.Reading $result[] = AirMonitoring.readingsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return readings (        );
            } finally {
                _releaseReply ($in);
            }
  } // readings

  public AirMonitoring.Reading[] alarms ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("alarms", true);
                $in = _invoke ($out);
                AirMonitoring.Reading $result[] = AirMonitoring.alarmsHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return alarms (        );
            } finally {
                _releaseReply ($in);
            }
  } // alarms

  public void registerMonitoringStation (AirMonitoring.StationInfo info)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerMonitoringStation", true);
                AirMonitoring.StationInfoHelper.write ($out, info);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registerMonitoringStation (info        );
            } finally {
                _releaseReply ($in);
            }
  } // registerMonitoringStation

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AirMonitoring/RegionalCentre:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RegionalCentreStub
