package AirMonitoring;


/**
* AirMonitoring/Agency.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public final class Agency implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String region_of_interest = null;
  public String contact_details = null;

  public Agency ()
  {
  } // ctor

  public Agency (String _name, String _region_of_interest, String _contact_details)
  {
    name = _name;
    region_of_interest = _region_of_interest;
    contact_details = _contact_details;
  } // ctor

} // class Agency
