package AirMonitoring;

/**
* AirMonitoring/AgencyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public final class AgencyHolder implements org.omg.CORBA.portable.Streamable
{
  public AirMonitoring.Agency value = null;

  public AgencyHolder ()
  {
  }

  public AgencyHolder (AirMonitoring.Agency initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AirMonitoring.AgencyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AirMonitoring.AgencyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AirMonitoring.AgencyHelper.type ();
  }

}
