package AirMonitoring;

/**
* AirMonitoring/AlarmHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public final class AlarmHolder implements org.omg.CORBA.portable.Streamable
{
  public AirMonitoring.Alarm value = null;

  public AlarmHolder ()
  {
  }

  public AlarmHolder (AirMonitoring.Alarm initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AirMonitoring.AlarmHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AirMonitoring.AlarmHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AirMonitoring.AlarmHelper.type ();
  }

}
