package AirMonitoring;


/**
* AirMonitoring/Alarm.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public final class Alarm implements org.omg.CORBA.portable.IDLEntity
{
  public String centre_name = null;
  public AirMonitoring.Reading alarm_readings[] = null;

  public Alarm ()
  {
  } // ctor

  public Alarm (String _centre_name, AirMonitoring.Reading[] _alarm_readings)
  {
    centre_name = _centre_name;
    alarm_readings = _alarm_readings;
  } // ctor

} // class Alarm
