package AirMonitoring;


/**
* AirMonitoring/alarmsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Wednesday, 11 April 2018 16:32:11 o'clock BST
*/

public final class alarmsHolder implements org.omg.CORBA.portable.Streamable
{
  public AirMonitoring.Reading value[] = null;

  public alarmsHolder ()
  {
  }

  public alarmsHolder (AirMonitoring.Reading[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AirMonitoring.alarmsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AirMonitoring.alarmsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AirMonitoring.alarmsHelper.type ();
  }

}
