package AirMonitoring;


/**
* AirMonitoring/CentreInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Sunday, 8 April 2018 17:51:22 o'clock BST
*/

public final class CentreInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String centre_name = null;
  public String location = null;
  public String IOR = null;

  public CentreInfo ()
  {
  } // ctor

  public CentreInfo (String _centre_name, String _location, String _IOR)
  {
    centre_name = _centre_name;
    location = _location;
    IOR = _IOR;
  } // ctor

} // class CentreInfo
