package AirMonitoring;


/**
* AirMonitoring/CentreInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public final class CentreInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String centre_name = null;
  public String location = null;

  public CentreInfo ()
  {
  } // ctor

  public CentreInfo (String _centre_name, String _location)
  {
    centre_name = _centre_name;
    location = _location;
  } // ctor

} // class CentreInfo
