package AirMonitoring;

/**
* AirMonitoring/CentreInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 10 April 2018 13:29:09 o'clock BST
*/

public final class CentreInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public AirMonitoring.CentreInfo value = null;

  public CentreInfoHolder ()
  {
  }

  public CentreInfoHolder (AirMonitoring.CentreInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AirMonitoring.CentreInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AirMonitoring.CentreInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AirMonitoring.CentreInfoHelper.type ();
  }

}
