package AirMonitoring;


/**
* AirMonitoring/EnvironmentalCentre.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 10 April 2018 13:29:09 o'clock BST
*/

public interface EnvironmentalCentre extends EnvironmentalCentreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EnvironmentalCentre
