package AirMonitoring;

/**
* AirMonitoring/EnvironmentalCentreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Sunday, 8 April 2018 17:51:22 o'clock BST
*/

public final class EnvironmentalCentreHolder implements org.omg.CORBA.portable.Streamable
{
  public AirMonitoring.EnvironmentalCentre value = null;

  public EnvironmentalCentreHolder ()
  {
  }

  public EnvironmentalCentreHolder (AirMonitoring.EnvironmentalCentre initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AirMonitoring.EnvironmentalCentreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AirMonitoring.EnvironmentalCentreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AirMonitoring.EnvironmentalCentreHelper.type ();
  }

}
