package AirMonitoring;


/**
* AirMonitoring/EnvironmentalCentrePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public abstract class EnvironmentalCentrePOA extends org.omg.PortableServer.Servant
 implements AirMonitoring.EnvironmentalCentreOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("all_readings", new java.lang.Integer (0));
    _methods.put ("get_readings", new java.lang.Integer (1));
    _methods.put ("_get_connected_centres", new java.lang.Integer (2));
    _methods.put ("register_regional_centre", new java.lang.Integer (3));
    _methods.put ("unregister_regional_centre", new java.lang.Integer (4));
    _methods.put ("raise_alarm", new java.lang.Integer (5));
    _methods.put ("register_agency", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AirMonitoring/EnvironmentalCentre/all_readings
       {
         AirMonitoring.Reading $result[] = null;
         $result = this.all_readings ();
         out = $rh.createReply();
         AirMonitoring.readingsHelper.write (out, $result);
         break;
       }

       case 1:  // AirMonitoring/EnvironmentalCentre/get_readings
       {
         String centre_name = in.read_string ();
         AirMonitoring.Reading $result[] = null;
         $result = this.get_readings (centre_name);
         out = $rh.createReply();
         AirMonitoring.readingsHelper.write (out, $result);
         break;
       }

       case 2:  // AirMonitoring/EnvironmentalCentre/_get_connected_centres
       {
         AirMonitoring.CentreInfo $result[] = null;
         $result = this.connected_centres ();
         out = $rh.createReply();
         AirMonitoring.centreListHelper.write (out, $result);
         break;
       }

       case 3:  // AirMonitoring/EnvironmentalCentre/register_regional_centre
       {
         AirMonitoring.CentreInfo info = AirMonitoring.CentreInfoHelper.read (in);
         this.register_regional_centre (info);
         out = $rh.createReply();
         break;
       }

       case 4:  // AirMonitoring/EnvironmentalCentre/unregister_regional_centre
       {
         AirMonitoring.CentreInfo info = AirMonitoring.CentreInfoHelper.read (in);
         this.unregister_regional_centre (info);
         out = $rh.createReply();
         break;
       }

       case 5:  // AirMonitoring/EnvironmentalCentre/raise_alarm
       {
         AirMonitoring.Alarm alarm = AirMonitoring.AlarmHelper.read (in);
         this.raise_alarm (alarm);
         out = $rh.createReply();
         break;
       }

       case 6:  // AirMonitoring/EnvironmentalCentre/register_agency
       {
         AirMonitoring.Agency agency = AirMonitoring.AgencyHelper.read (in);
         this.register_agency (agency);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AirMonitoring/EnvironmentalCentre:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public EnvironmentalCentre _this() 
  {
    return EnvironmentalCentreHelper.narrow(
    super._this_object());
  }

  public EnvironmentalCentre _this(org.omg.CORBA.ORB orb) 
  {
    return EnvironmentalCentreHelper.narrow(
    super._this_object(orb));
  }


} // class EnvironmentalCentrePOA
