package AirMonitoring;


/**
* AirMonitoring/MonitoringStationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 10 April 2018 13:29:09 o'clock BST
*/

public interface MonitoringStationOperations 
{
  AirMonitoring.Reading reading ();
  AirMonitoring.Reading[] reading_log ();
  void take_reading ();
  void setInfo (AirMonitoring.StationInfo info);
  AirMonitoring.StationInfo getInfo ();
  void turn_on ();
  void turn_off ();
  void reset ();
} // interface MonitoringStationOperations
