package AirMonitoring;


/**
* AirMonitoring/Reading.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public final class Reading implements org.omg.CORBA.portable.IDLEntity
{
  public int time = (int)0;
  public int date = (int)0;
  public String station_name = null;
  public int reading_value = (int)0;

  public Reading ()
  {
  } // ctor

  public Reading (int _time, int _date, String _station_name, int _reading_value)
  {
    time = _time;
    date = _date;
    station_name = _station_name;
    reading_value = _reading_value;
  } // ctor

} // class Reading
