package AirMonitoring;


/**
* AirMonitoring/readingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public final class readingsHolder implements org.omg.CORBA.portable.Streamable
{
  public AirMonitoring.Reading value[] = null;

  public readingsHolder ()
  {
  }

  public readingsHolder (AirMonitoring.Reading[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AirMonitoring.readingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AirMonitoring.readingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AirMonitoring.readingsHelper.type ();
  }

}
