package AirMonitoring;


/**
* AirMonitoring/RegionalCentreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public interface RegionalCentreOperations 
{
  AirMonitoring.StationInfo[] connected_devices ();
  AirMonitoring.CentreInfo get_centre_info ();
  void set_info (AirMonitoring.CentreInfo info);
  AirMonitoring.Reading[] all_readings ();
  AirMonitoring.Reading[] get_readings (String station_name);
  AirMonitoring.Reading[] get_current_readings ();
  AirMonitoring.Reading[] alarms ();
  void register_monitoring_station (AirMonitoring.StationInfo info);
  void raise_alarm (AirMonitoring.Reading reading);
} // interface RegionalCentreOperations
