package AirMonitoring;


/**
* AirMonitoring/RegionalCentreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 10 April 2018 13:29:09 o'clock BST
*/

public interface RegionalCentreOperations 
{
  AirMonitoring.StationInfo[] connectedDevices ();
  void connectedDevices (AirMonitoring.StationInfo[] newConnectedDevices);
  AirMonitoring.CentreInfo centreInfo ();
  void setInfo (AirMonitoring.CentreInfo info);
  AirMonitoring.Reading[] allReadings ();
  AirMonitoring.Reading[] readings (String station_name);
  AirMonitoring.Reading[] alarms ();
  void registerMonitoringStation (AirMonitoring.StationInfo info);
} // interface RegionalCentreOperations
