package AirMonitoring;


/**
* AirMonitoring/RegionalCentre.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Sunday, 8 April 2018 17:51:22 o'clock BST
*/

public interface RegionalCentre extends RegionalCentreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RegionalCentre
