package AirMonitoring;


/**
* AirMonitoring/RegionalCentre.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public interface RegionalCentre extends RegionalCentreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RegionalCentre
