package AirMonitoring;


/**
* AirMonitoring/RegionalCentreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Sunday, 8 April 2018 17:51:22 o'clock BST
*/

public interface RegionalCentreOperations 
{
  AirMonitoring.StationInfo[] connectedDevices ();
  void connectedDevices (AirMonitoring.StationInfo[] newConnectedDevices);
  AirMonitoring.CentreInfo centreInfo ();
  void setInfo (AirMonitoring.CentreInfo info);
  AirMonitoring.Reading[] readings ();
  AirMonitoring.Reading[] alarms ();
  void registerMonitoringStation (AirMonitoring.StationInfo info);
} // interface RegionalCentreOperations
