package AirMonitoring;


/**
* AirMonitoring/RegionalCentrePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Sunday, 8 April 2018 17:51:22 o'clock BST
*/

public abstract class RegionalCentrePOA extends org.omg.PortableServer.Servant
 implements AirMonitoring.RegionalCentreOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_connectedDevices", new java.lang.Integer (0));
    _methods.put ("_set_connectedDevices", new java.lang.Integer (1));
    _methods.put ("centreInfo", new java.lang.Integer (2));
    _methods.put ("setInfo", new java.lang.Integer (3));
    _methods.put ("readings", new java.lang.Integer (4));
    _methods.put ("alarms", new java.lang.Integer (5));
    _methods.put ("registerMonitoringStation", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AirMonitoring/RegionalCentre/_get_connectedDevices
       {
         AirMonitoring.StationInfo $result[] = null;
         $result = this.connectedDevices ();
         out = $rh.createReply();
         AirMonitoring.stationListHelper.write (out, $result);
         break;
       }

       case 1:  // AirMonitoring/RegionalCentre/_set_connectedDevices
       {
         AirMonitoring.StationInfo newConnectedDevices[] = AirMonitoring.stationListHelper.read (in);
         this.connectedDevices (newConnectedDevices);
         out = $rh.createReply();
         break;
       }

       case 2:  // AirMonitoring/RegionalCentre/centreInfo
       {
         AirMonitoring.CentreInfo $result = null;
         $result = this.centreInfo ();
         out = $rh.createReply();
         AirMonitoring.CentreInfoHelper.write (out, $result);
         break;
       }

       case 3:  // AirMonitoring/RegionalCentre/setInfo
       {
         AirMonitoring.CentreInfo info = AirMonitoring.CentreInfoHelper.read (in);
         this.setInfo (info);
         out = $rh.createReply();
         break;
       }

       case 4:  // AirMonitoring/RegionalCentre/readings
       {
         AirMonitoring.Reading $result[] = null;
         $result = this.readings ();
         out = $rh.createReply();
         AirMonitoring.readingsHelper.write (out, $result);
         break;
       }

       case 5:  // AirMonitoring/RegionalCentre/alarms
       {
         AirMonitoring.Reading $result[] = null;
         $result = this.alarms ();
         out = $rh.createReply();
         AirMonitoring.alarmsHelper.write (out, $result);
         break;
       }

       case 6:  // AirMonitoring/RegionalCentre/registerMonitoringStation
       {
         AirMonitoring.StationInfo info = AirMonitoring.StationInfoHelper.read (in);
         this.registerMonitoringStation (info);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AirMonitoring/RegionalCentre:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RegionalCentre _this() 
  {
    return RegionalCentreHelper.narrow(
    super._this_object());
  }

  public RegionalCentre _this(org.omg.CORBA.ORB orb) 
  {
    return RegionalCentreHelper.narrow(
    super._this_object(orb));
  }


} // class RegionalCentrePOA
