package AirMonitoring;

/**
* AirMonitoring/RegionalCentreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 10 April 2018 13:29:09 o'clock BST
*/

public final class RegionalCentreHolder implements org.omg.CORBA.portable.Streamable
{
  public AirMonitoring.RegionalCentre value = null;

  public RegionalCentreHolder ()
  {
  }

  public RegionalCentreHolder (AirMonitoring.RegionalCentre initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AirMonitoring.RegionalCentreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AirMonitoring.RegionalCentreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AirMonitoring.RegionalCentreHelper.type ();
  }

}
