package AirMonitoring;


/**
* AirMonitoring/RegionalCentrePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public abstract class RegionalCentrePOA extends org.omg.PortableServer.Servant
 implements AirMonitoring.RegionalCentreOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_connected_devices", new java.lang.Integer (0));
    _methods.put ("get_centre_info", new java.lang.Integer (1));
    _methods.put ("set_info", new java.lang.Integer (2));
    _methods.put ("all_readings", new java.lang.Integer (3));
    _methods.put ("get_readings", new java.lang.Integer (4));
    _methods.put ("get_current_readings", new java.lang.Integer (5));
    _methods.put ("alarms", new java.lang.Integer (6));
    _methods.put ("register_monitoring_station", new java.lang.Integer (7));
    _methods.put ("raise_alarm", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AirMonitoring/RegionalCentre/_get_connected_devices
       {
         AirMonitoring.StationInfo $result[] = null;
         $result = this.connected_devices ();
         out = $rh.createReply();
         AirMonitoring.stationListHelper.write (out, $result);
         break;
       }

       case 1:  // AirMonitoring/RegionalCentre/get_centre_info
       {
         AirMonitoring.CentreInfo $result = null;
         $result = this.get_centre_info ();
         out = $rh.createReply();
         AirMonitoring.CentreInfoHelper.write (out, $result);
         break;
       }

       case 2:  // AirMonitoring/RegionalCentre/set_info
       {
         AirMonitoring.CentreInfo info = AirMonitoring.CentreInfoHelper.read (in);
         this.set_info (info);
         out = $rh.createReply();
         break;
       }

       case 3:  // AirMonitoring/RegionalCentre/all_readings
       {
         AirMonitoring.Reading $result[] = null;
         $result = this.all_readings ();
         out = $rh.createReply();
         AirMonitoring.readingsHelper.write (out, $result);
         break;
       }

       case 4:  // AirMonitoring/RegionalCentre/get_readings
       {
         String station_name = in.read_string ();
         AirMonitoring.Reading $result[] = null;
         $result = this.get_readings (station_name);
         out = $rh.createReply();
         AirMonitoring.readingsHelper.write (out, $result);
         break;
       }

       case 5:  // AirMonitoring/RegionalCentre/get_current_readings
       {
         AirMonitoring.Reading $result[] = null;
         $result = this.get_current_readings ();
         out = $rh.createReply();
         AirMonitoring.readingsHelper.write (out, $result);
         break;
       }

       case 6:  // AirMonitoring/RegionalCentre/alarms
       {
         AirMonitoring.Reading $result[] = null;
         $result = this.alarms ();
         out = $rh.createReply();
         AirMonitoring.readingsHelper.write (out, $result);
         break;
       }

       case 7:  // AirMonitoring/RegionalCentre/register_monitoring_station
       {
         AirMonitoring.StationInfo info = AirMonitoring.StationInfoHelper.read (in);
         this.register_monitoring_station (info);
         out = $rh.createReply();
         break;
       }

       case 8:  // AirMonitoring/RegionalCentre/raise_alarm
       {
         AirMonitoring.Reading reading = AirMonitoring.ReadingHelper.read (in);
         this.raise_alarm (reading);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AirMonitoring/RegionalCentre:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RegionalCentre _this() 
  {
    return RegionalCentreHelper.narrow(
    super._this_object());
  }

  public RegionalCentre _this(org.omg.CORBA.ORB orb) 
  {
    return RegionalCentreHelper.narrow(
    super._this_object(orb));
  }


} // class RegionalCentrePOA
