package AirMonitoring;


/**
* AirMonitoring/StationInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Sunday, 8 April 2018 17:51:22 o'clock BST
*/

public final class StationInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String station_name = null;
  public String location = null;
  public String IOR = null;

  public StationInfo ()
  {
  } // ctor

  public StationInfo (String _station_name, String _location, String _IOR)
  {
    station_name = _station_name;
    location = _location;
    IOR = _IOR;
  } // ctor

} // class StationInfo
