package AirMonitoring;


/**
* AirMonitoring/StationInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AirMonitoring.idl
* Tuesday, 17 April 2018 11:24:36 o'clock BST
*/

public final class StationInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String station_name = null;
  public String location = null;

  public StationInfo ()
  {
  } // ctor

  public StationInfo (String _station_name, String _location)
  {
    station_name = _station_name;
    location = _location;
  } // ctor

} // class StationInfo
